### ISSUE TITLE
Create a low fidelity mockup of the application

### ISSUE THREAD

**Issue by ericrfdev** [vlab-research/vlab#11]
The purpose of the low fidelity mockup is to iterate it as needed to answer:

- Which features do we want for the MVP ?
- Visual hierarchy for each feature or main area of the app

and to be in the same page about the expected layout of the app.

**Comment by ericrfdev** [comment]
Hi @nandanrao !! 
I created a couple of wireframes for the **Studies** and **Study Page** which are the UI pages that are going to be tackled first.
I also defined some of the behaviours and interactions of the designed elements in the wireframe which will be helpful to have in development type.

**Studies page:** This page will display the name and creation date for the different studies
- Newest studies comes first
- Infinite scrolling to display all the studies (without virtual list for now)
- When loading more studies, a loading indicator is displayed at the end of the list
- When the tab is active, in the background we'll periodically poll the studies endpoint for newest studies. If new ones are found, will be added automatically to the top of the list and we'll let the user know that this happened
- In Desktop and Table Screen Sizes:
-  - The content is displayed inside a centered box which grows as more studies are displayed (instead of being fixed size with scrolling inside)
- - The whole page scrolls, the title of the page is not fixed. The only thing that is fixed is the sidebar
- - The name of the studies is truncated after two lines(I'm assuming names of studies are big, but if it's not the case @nandanrao we will truncate at 1 which facilitate things)
- In Mobile Screen Sizes:
-  - The list of studies is displayed without a box
-  - The name of the studies is truncated after X lines
-  - The creation date of the studies is listed either at the right of the study row like in desktop or below the name (pick the one that looks best when implementing it)
- No sorting functionality for now.
- - This will require some extra backend and frontend work and I think this feature is not necessary for now
- - The default order needs to be, newest studies comes first
- No search functionality for now
- - This will require some extra backend and frontend work and I think this feature is not necessary for now
- - We'll not have people with lots of studies at first to justify the feature at this stage

![image](https://user-images.githubusercontent.com/84807811/122688253-84450d80-d21b-11eb-8d08-9e7dbe92f396.png)

**Study page:** This page will display all the data related to an specific study and the different segments of participants (Stratum) it has defined.
- back button at the left of the title
- the studies page link in the sidebar is not selected anymore
- date-range selector at the top-right of the page
- title, back button and date-range selector and not fixed, whole page is scrollable except for the sidebar
- There is a centered box like in the studies page.
- At the top of the centered box, we display the current state (specified by the date range selector) for different data that changes over time for an study.
- By clicking one of the 4 boxes, the linechart below them is updated to refect  its overtime data given the ranges specified in the date range selector
- Below the line-chart there are 3 tables that display the current state (last date specified on the date range selector) for the different segments of participants
- If last-date specified in the selector is today, when the tab is active, the info is refreshed at an interval yet to define @nandanrao 
- tablet and mobile screen sizes:
- - UI components and content will be adapted as needed so it looks good on any screen size.

![image](https://user-images.githubusercontent.com/84807811/122688267-a2ab0900-d21b-11eb-9c17-516e00055580.png)

![image](https://user-images.githubusercontent.com/84807811/122688286-b5254280-d21b-11eb-9f16-c9fc1f992f3f.png)

**Comment by nandanrao** [comment]
Overall looks great!! Very happy about this!

1. Studies page sounds good - I think truncating to one line is fine! I don't see the need for polling, it's not really a multi-user situation so I don't think a study is created unless the user themselves created a study! So unless it shows other data on that page, that shouldn't be needed. 

2. I think the sidebar is wasted space. It basically just provides a "home" link, a logout, and the name of the person logged in. I would move that to a top nav bar to not lose so much space!

3. I like the idea of clicking one of the 4 boxes and seeing the line chart - very cool!!!

4. Yeah as far as interval refresh - I dunno! 30 seconds?

**Comment by ericrfdev** [comment]
Hey @nandanrao !! I'm glad that you like it 🙌

Yes you're right about the polling, it's not necessary. When I wrote this, I was thinking about the case were the tab is never closed, but as you said the user is aware of the studies he created so if he created an study and it's not there, his first instict will be to refresh. Also now that I think of it, this scenario will not be common because I plan to use react-query for data-fetching, and this library by default re-fetches on the background stale data when the browser tab becomes active.

Good point about the sidebar 👍  I agree that it's wasted space right now, I'll implement a navbar.

Yes, 30 seconds refresh sounds good to me 👌
