### ISSUE TITLE
Spike to choose a solution/product for managing authentication and authorization

### ISSUE THREAD

**Issue by ericrfdev** [vlab-research/vlab#12]

**Comment by nandanrao** [comment]
Let's go with a fully open-source solution. 

I like the look of https://www.ory.sh/. 

We would want Kratos for all identity management tasks. We should use our database for user storage. 

Probably want to protect server(s) by just using their OathKeeper proxy. This makes it super easy to have the client talk to multiple backends as well, which is nice.

**Comment by ericrfdev** [comment]
After investigating more about Ory and specially Ory Kratos, we decided to use Auth0 for both authentication and authorization.

We think that Ory products are great, but at this stage we think that it makes more sense for us to use a managed solution.

Some of the reasons that made us choose Auth0 instead of Ory Kratos:
- More complex and slow to implement compared to using an external service such as Auth0
- Maintenance is much higher, specially in the form of required updates (ex. security patches). 
- The software is production ready but as listed in their documentation Ory Kratos **may change in unpredictable ways** (more info here: https://www.ory.sh/docs/ecosystem/versioning#maturity)
- No official examples on how to implement the different flows using an SPA.
- It only supports cookies, no support for json web tokens. If you want your backend to operate on json web tokens, you'll need to add a proxy in between your frontend and api that obtains the user info from an Ory Kratos endpoint using the cookie and create a jwt from it.
- There's no way to refresh a session. You can modify the session expiration date but when it expires, the user will be forced to write his credentials again
- Community is much smaller compared to Auth0 and this is important when issues appear.
- Documentation is great, but since the products are changing fast it's not 100% updated.
- I haven't seen that they support hooks for the different flows. (eg. making a request to specified endpoint after the user register)
- You're required to implement the UI for the different flows (login, register, forgot password,...)
