### ISSUE TITLE
Render basic question types in survey

### ISSUE THREAD

**Issue by nandanrao** [vlab-research/vlab#59]
This task mostly involves deciding how these types look like / styling them. But also includes the creation of a couple of components. 

DoD

* Given the Typeform JSON of a multiple choice field, I can render a user-interface to answer the question with a component.
* Given the Typeform JSON of a short-text field, I can render a user-interface to answer the question with a component.

**Comment by sssoja** [comment]
https://sustainablewww.org/principles/how-to-implement-routes-in-your-svelte-web-application-using-svelte-routing

**Comment by sssoja** [comment]
[This](https://codechips.me/svelte-ssr-and-router-recommendation/) is also interesting
